### ISSUE TITLE
Image art not converted properly

### ISSUE THREAD

**Issue by alcuin2k** [retro-esp32/Convert-Image-to-ROM-art#1]
**Describe the bug**
Image art not converted properly.

**To Reproduce**
1. upload images in album url.
https://imgur.com/a/feXzyIN
I have tried jpg, png, resizing to 50%. Some images convert correctly, others display corruption.

**Expected behavior**
Image art converted correctly

**Screenshots**
![20200310_213202](https://user-images.githubusercontent.com/44350353/76376788-356db000-6317-11ea-87d1-213aa00e72f4.jpg)

images used
https://imgur.com/a/feXzyIN

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version 80

**Additional context**
n/a

**Comment by alcuin2k** [comment]
After reviewing the js conversion code, I resized my pics to 176 width and the conversion works now, thanks.

**Comment by 32teeth** [comment]
Sorry for the late response
Looks like you figured it out.
